name: WorldBorder
author: Brettflan
description: Efficient, feature-rich plugin for limiting the size of your worlds.
version: 1.7.6
main: com.wimbli.WorldBorder.WorldBorder
softdepend:
  - dynmap
commands:
  wborder:
    description: Primary command for WorldBorder.
    aliases: [worldborder, wb]
    usage: |
           /<command> - list available commands (show help).
           /<command> set <radiusX> [radiusZ] - set world border, centered on you.
           /<command> [world] set <radiusX> [radiusZ] <x> <z> - set world border.
           /<command> [world] setcorners <x1> <z1> <x2> <z2> - set border from corners.
           /<command> [world] radius <radiusX> [radiusZ] - change border's radius.
           /<command> [world] clear - remove border for this world.
           /<command> clear all - remove border for all worlds.
           /<command> list - show border information for all worlds.
           /<command> shape <elliptic|rectangular> - set the default border shape.
           /<command> shape <round|square> - same as above, backwards compatible.
           /<command> getmsg - display border message.
           /<command> setmsg <text> - set border message.
           /<command> knockback <distance> - how far to move the player back.
           /<command> whoosh <on/off> - turn knockback effect on or off.
           /<command> portal <on/off> - turn portal redirection on or off.
           /<command> delay <amount> - time between border checks.
           /<command> wshape [world] <elliptic|rectangular|default> - override shape.
           /<command> wshape [world] <round|square|default> - same as above values.
           /<command> wrap [world] <on/off> - can make border crossings wrap around.
           /<command> [world] fill [freq] [pad] [force] - generate world to border.
           /<command> [world] trim [freq] [pad] - trim world outside of border.
           /<command> bypass [player] [on/off] - let player go beyond border.
           /<command> bypasslist - list players with border bypass enabled.
           /<command> remount <amount> - delay before remounting after knockback.
           /<command> dynmap <on/off> - turn DynMap border display on or off.
           /<command> dynmapmsg <text> - DynMap border labels will show this.
           /<command> debug <on/off> - turn debug mode on or off.
permissions:
  worldborder.*:
    description: Grants all WorldBorder permissions
    children:
      worldborder.set: true
      worldborder.radius: true
      worldborder.clear: true
      worldborder.list: true
      worldborder.shape: true
      worldborder.getmsg: true
      worldborder.setmsg: true
      worldborder.reload: true
      worldborder.debug: true
      worldborder.knockback: true
      worldborder.delay: true
      worldborder.wshape: true
      worldborder.fill: true
      worldborder.trim: true
      worldborder.help: true
      worldborder.whoosh: true
      worldborder.dynmap: true
      worldborder.dynmapmsg: true
      worldborder.bypass: true
      worldborder.bypasslist: true
      worldborder.wrap: true
      worldborder.portal: true
      worldborder.remount: true
  worldborder.set:
    description: Can set borders for any world
    default: op
  worldborder.radius:
    description: Can set the radius of an existing border
    default: op
  worldborder.clear:
    description: Can remove any border
    default: op
  worldborder.list:
    description: Can view a list of all borders
    default: op
  worldborder.shape:
    description: Can set the default shape (round or square) for all borders
    default: op
  worldborder.getmsg:
    description: Can view the border crossing message
    default: op
  worldborder.setmsg:
    description: Can set the border crossing message
    default: op
  worldborder.reload:
    description: Can force the plugin to reload from the config file
    default: op
  worldborder.debug:
    description: Can enable/disable debug output to console
    default: op
  worldborder.knockback:
    description: Can set the knockback distance for border crossings
    default: op
  worldborder.delay:
    description: Can set the frequency at which the plugin checks for border crossings
    default: op
  worldborder.wshape:
    description: Can set an overriding border shape for a single world
    default: op
  worldborder.wrap:
    description: Can set border crossings to wrap around to the other side of the world
    default: op
  worldborder.fill:
    description: Can fill in (generate) any missing map chunks out to the border
    default: op
  worldborder.trim:
    description: Can trim (remove) any excess map chunks outside of the border
    default: op
  worldborder.help:
    description: Can view the command reference help pages
    default: op
  worldborder.whoosh:
    description: Can enable/disable "whoosh" knockback effect
    default: op
  worldborder.portal:
    description: Can enable/disable portal redirection to be inside border
    default: op
  worldborder.remount:
    description: Can set the delay before remounting a player to their vehicle after knockback
    default: op
  worldborder.dynmap:
    description: Can enable/disable DynMap border display integration
    default: op
  worldborder.dynmapmsg:
    description: Can set the label text for borders shown in DynMap
    default: op
  worldborder.bypass:
    description: Can enable bypass mode to go beyond the border
    default: op
  worldborder.bypasslist:
    description: Can get list of players with border bypass enabled
    default: op
